name: bb-linked-NESTED-8e70af6434b849
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  synthetic:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "bb-linked-NESTED-8e70af6434b849"
