name: BugBase WRP Allowed Actions action-docker-unallowed-second

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  synthetic-probe:
    runs-on: ubuntu-latest
    steps:
      - name: Unallowed Docker container action
        uses: docker://busybox:1.36.1
        with:
          entrypoint: /bin/echo
          args: bb-wrp-runtime-action-docker-unallowed-second-dryrun-ms3c2qot-docker-action
      - name: Marker after Docker container action
        run: echo "bb-wrp-runtime-action-docker-unallowed-second-dryrun-ms3c2qot"
